### ISSUE TITLE
Relevance of support address and telecom on Practitioner?

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#71]
..
I am not sure about the recording of address and telecom on the Practitioner itself, these are often (except perhaps mobile, although arguable) in the context of a particular role/location/organization. Practitioners may not like to disclose their private contact details.
I notice that PD2 IG does not include address or telecom on Practitioner.

_Originally posted by @heathfrankel in https://github.com/hl7au/au-fhir-core/discussions/37#discussioncomment-7076159_

**Comment by dt-r** [comment]
Discussed in [2023-09-28 AU Core TDG Agenda/Minutes](https://confluence.hl7.org/pages/viewpage.action?pageId=184920587). 

- Questions raised on is there ever a time when you have only Practitioner and not PractitionerRole? GG clarified that this is sometimes case in secondary messaging or messaging between the organisation and its practitioners
- General discussion that Practitioners are in context of PractitionerRole
- Discussion that this is optional, so possibly leave as is in AU Core and don't remove it, as there is no other place to mention this otherwise
- Concern on definition specifying private - DTR noted this was a bug, was not meant to be introduced in there and noted to fix.
- Discussion on purpose of these elements on Practitioner - it's to provide a non-role specific endpoint for addressing comms
- GG noted that incumbent on group to consider context of International and other national specifications. In these cases we should be looking at what is in US Core and considering relevance. 
- Agreement to review Practitioner.address and Practitioner.telecom against US Core and come back to group. For discussion on relevance to AU Core.

**Comment by dbojicic** [comment]
[US Core Practitioner](https://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-practitioner.html) flags telecom and address, and some of their sub-elements, as Must Support. Following are Must Support:
* telecom
  * system
  * value
* address
  * line
  * city
  * state
  * postalCode
  * country

Both telecom and address are optional in the US Core Practitioner profile. The profile does include implementation guidance that points out that only the practitioner's workplace contact information **SHOULD** be made available to the patients in order to protect practitioner's privacy. 

IPS profile [Practitioner (IPS)](https://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-Practitioner-uv-ips.html) flags both telecom and address as Must Support: 
* telecom
* address

Both elements are optional in the IPS Practitioner profile.

**Comment by dbojicic** [comment]
@heathfrankel, please see above for comments on the US Core & IPS support for Practitioner telecom and address. 

Considering both address and telecom are in US Core and IPS, do you still want to bring the discussion about leaving them out of AU Core (and why) to the TDG?

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43860](https://jira.hl7.org/browse/FHIR-43860).

Questions on this profile or how to use the Practitioner resource can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia
